[package]
name = "searchllama-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
reqwest = { version = "^0.12", features = ["stream", "json"] }
futures = "^0.3"
log = "^0.4"
console_log = "^1"
lazy_static = "^1"