[package]
name = "searchllama-web"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "^0.21", features = ["csr"] }
lazy_static = "1.4.0"
wasm-bindgen-futures = "^0.4"
console_log = "^1"
log = "^0.4"